import { NextResponse } from "next/server";
import prisma from "@/lib/db";

// POST - Generate ESG Report
export async function POST() {
  try {
    const company = await prisma.company.findFirst();
    if (!company) {
      return NextResponse.json({ error: "Company not found" }, { status: 404 });
    }

    // Get all data
    const emissions = await prisma.emission.findMany({
      where: { companyId: company.id },
      orderBy: { date: "desc" },
    });

    const water = await prisma.waterUsage.findMany({
      where: { companyId: company.id },
      orderBy: { date: "desc" },
    });

    const waste = await prisma.wasteData.findMany({
      where: { companyId: company.id },
      orderBy: { date: "desc" },
    });

    // Calculate totals
    const totalEmissions = emissions.reduce((sum, e) => sum + e.amount, 0);
    const totalWater = water.reduce((sum, w) => sum + w.amount, 0);
    const totalWaste = waste.reduce((sum, w) => sum + w.amount, 0);

    // Calculate by category
    const emissionsByCategory: Record<string, number> = {};
    emissions.forEach((e) => {
      emissionsByCategory[e.category] = (emissionsByCategory[e.category] || 0) + e.amount;
    });

    const waterByCategory: Record<string, number> = {};
    water.forEach((w) => {
      waterByCategory[w.category] = (waterByCategory[w.category] || 0) + w.amount;
    });

    const wasteByCategory: Record<string, number> = {};
    waste.forEach((w) => {
      wasteByCategory[w.category] = (wasteByCategory[w.category] || 0) + w.amount;
    });

    // Generate report text
    const reportDate = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const report = `
================================================================================
                          ESG SUSTAINABILITY REPORT
================================================================================

Company: ${company.name}
Industry: ${company.industry || "Not specified"}
Report Date: ${reportDate}

================================================================================
                              EXECUTIVE SUMMARY
================================================================================

Total Carbon Emissions: ${totalEmissions.toLocaleString()} kg CO2e
Total Water Usage: ${totalWater.toLocaleString()} liters
Total Waste: ${totalWaste.toLocaleString()} kg

================================================================================
                           CARBON EMISSIONS BREAKDOWN
================================================================================

${Object.entries(emissionsByCategory)
  .map(([cat, amt]) => `${cat.charAt(0).toUpperCase() + cat.slice(1)}: ${amt.toLocaleString()} kg CO2e`)
  .join("\n") || "No emissions data recorded."}

Total Entries: ${emissions.length}

================================================================================
                            WATER USAGE BREAKDOWN
================================================================================

${Object.entries(waterByCategory)
  .map(([cat, amt]) => `${cat.charAt(0).toUpperCase() + cat.slice(1)}: ${amt.toLocaleString()} liters`)
  .join("\n") || "No water usage data recorded."}

Total Entries: ${water.length}

================================================================================
                             WASTE METRICS BREAKDOWN
================================================================================

${Object.entries(wasteByCategory)
  .map(([cat, amt]) => `${cat.charAt(0).toUpperCase() + cat.slice(1)}: ${amt.toLocaleString()} kg`)
  .join("\n") || "No waste data recorded."}

Total Entries: ${waste.length}

================================================================================
                              COMPLIANCE STATUS
================================================================================

This report provides a summary of environmental metrics tracked by ${company.name}.
Data should be verified against primary sources for official compliance submissions.

Report generated by ESG Reporter
================================================================================
`;

    // Save report to database
    await prisma.report.create({
      data: {
        companyId: company.id,
        period: new Date().toISOString().slice(0, 7), // YYYY-MM
        type: "monthly",
        totalEmissions,
        totalWater,
        totalWaste,
      },
    });

    // Return as downloadable text file
    return new NextResponse(report, {
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": `attachment; filename="esg-report-${new Date().toISOString().split("T")[0]}.txt"`,
      },
    });
  } catch (error) {
    console.error("Error generating report:", error);
    return NextResponse.json({ error: "Failed to generate report" }, { status: 500 });
  }
}
